package co.edu.unicauca.gui.vistas.articulos;

import co.edu.unicauca.gui.models.Articulo;
import co.edu.unicauca.gui.models.Conferencia;
import co.edu.unicauca.gui.servicios.ArticuloServices;
import java.util.List;
import java.util.stream.Collectors;

/**
 *
 * @author sonhuila
 */
public class VtnConsultarArticulo extends javax.swing.JInternalFrame {

    private ArticuloServices objArticuloServices;

    public VtnConsultarArticulo(ArticuloServices objArticuloServices) {
        initComponents();
        this.objArticuloServices = objArticuloServices;
        this.jLabelMostrarMensaje.setVisible(false);
        this.jPanelMostrarDatos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSuperior = new javax.swing.JPanel();
        jLabelTituloJForm = new javax.swing.JLabel();
        jPanelInferior = new javax.swing.JPanel();
        jPanelMedio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIdArticulo = new javax.swing.JTextField();
        jButtonConsultar = new javax.swing.JButton();
        jPanelMostrarDatos = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelAutores = new javax.swing.JLabel();
        jLabelResumen = new javax.swing.JLabel();
        jLabelIdArticulo = new javax.swing.JLabel();
        jLabelMAutores = new javax.swing.JLabel();
        jLabelMResumen = new javax.swing.JLabel();
        jLabelMIdArticulo = new javax.swing.JLabel();
        jLabelMNombre = new javax.swing.JLabel();
        jLabelMostrarMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelTituloJForm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTituloJForm.setForeground(new java.awt.Color(0, 51, 153));
        jLabelTituloJForm.setText("Consultar Articulo");

        javax.swing.GroupLayout jPanelSuperiorLayout = new javax.swing.GroupLayout(jPanelSuperior);
        jPanelSuperior.setLayout(jPanelSuperiorLayout);
        jPanelSuperiorLayout.setHorizontalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSuperiorLayout.createSequentialGroup()
                .addContainerGap(287, Short.MAX_VALUE)
                .addComponent(jLabelTituloJForm, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(282, 282, 282))
        );
        jPanelSuperiorLayout.setVerticalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabelTituloJForm)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelSuperior, java.awt.BorderLayout.PAGE_START);

        jPanelInferior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelInferiorLayout = new javax.swing.GroupLayout(jPanelInferior);
        jPanelInferior.setLayout(jPanelInferiorLayout);
        jPanelInferiorLayout.setHorizontalGroup(
            jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );
        jPanelInferiorLayout.setVerticalGroup(
            jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelInferior, java.awt.BorderLayout.PAGE_END);

        jPanelMedio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Id");

        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jPanelMostrarDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelNombre.setText("Nombre:");

        jLabelAutores.setText("Autores:");

        jLabelResumen.setText("Resumen:");

        jLabelIdArticulo.setText("Id Articulo:");

        jLabelMAutores.setText("resultado");

        jLabelMResumen.setText("resultado");

        jLabelMIdArticulo.setText("resultado");

        jLabelMNombre.setText("resultado");

        javax.swing.GroupLayout jPanelMostrarDatosLayout = new javax.swing.GroupLayout(jPanelMostrarDatos);
        jPanelMostrarDatos.setLayout(jPanelMostrarDatosLayout);
        jPanelMostrarDatosLayout.setHorizontalGroup(
            jPanelMostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMostrarDatosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelMostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelAutores)
                    .addComponent(jLabelResumen)
                    .addComponent(jLabelIdArticulo))
                .addGap(115, 115, 115)
                .addGroup(jPanelMostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMResumen)
                    .addComponent(jLabelMAutores)
                    .addComponent(jLabelMNombre)
                    .addComponent(jLabelMIdArticulo))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanelMostrarDatosLayout.setVerticalGroup(
            jPanelMostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMostrarDatosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelMIdArticulo)
                .addGap(12, 12, 12)
                .addComponent(jLabelMNombre)
                .addGap(16, 16, 16)
                .addComponent(jLabelMAutores)
                .addGap(12, 12, 12)
                .addComponent(jLabelMResumen)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMostrarDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelIdArticulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAutores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelResumen)
                .addGap(34, 34, 34))
        );

        jLabelMostrarMensaje.setText("Mensaje");

        javax.swing.GroupLayout jPanelMedioLayout = new javax.swing.GroupLayout(jPanelMedio);
        jPanelMedio.setLayout(jPanelMedioLayout);
        jPanelMedioLayout.setHorizontalGroup(
            jPanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMedioLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMostrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMostrarMensaje)
                    .addGroup(jPanelMedioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldIdArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonConsultar)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanelMedioLayout.setVerticalGroup(
            jPanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMedioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMostrarMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelMostrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMedio, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        String idArticulo = this.jTextFieldIdArticulo.getText();

        try {
            Integer idArticuloEntero = Integer.parseInt(idArticulo);

            if (this.objArticuloServices.consultarSiExisteArticulo(idArticuloEntero)) {
                this.jLabelMostrarMensaje.setVisible(false);
                this.jPanelMostrarDatos.setVisible(true);
                Articulo objArticulo = this.objArticuloServices.consultarArticulo(idArticuloEntero);

                this.jLabelMIdArticulo.setText(objArticulo.getIdArticulo() + "");
                this.jLabelMNombre.setText(objArticulo.getTitulo());
                this.jLabelMAutores.setText(objArticulo.getAutores());
                this.jLabelMResumen.setText(objArticulo.getResumen() + "");
            } else {
                this.jLabelMostrarMensaje.setVisible(true);
                this.jLabelMostrarMensaje.setText("Error, no existe un artículo con ese identificador");
                this.jPanelMostrarDatos.setVisible(false);
            }
        } catch (NumberFormatException e) {
            this.jLabelMostrarMensaje.setVisible(true);
            this.jLabelMostrarMensaje.setText("Error, el ID de artículo debe ser un número.");
            this.jPanelMostrarDatos.setVisible(false);
        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAutores;
    private javax.swing.JLabel jLabelIdArticulo;
    private javax.swing.JLabel jLabelMAutores;
    private javax.swing.JLabel jLabelMIdArticulo;
    private javax.swing.JLabel jLabelMNombre;
    private javax.swing.JLabel jLabelMResumen;
    private javax.swing.JLabel jLabelMostrarMensaje;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelResumen;
    private javax.swing.JLabel jLabelTituloJForm;
    private javax.swing.JPanel jPanelInferior;
    private javax.swing.JPanel jPanelMedio;
    private javax.swing.JPanel jPanelMostrarDatos;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JTextField jTextFieldIdArticulo;
    // End of variables declaration//GEN-END:variables
}
